M48
; DRILL file {KiCad (6.0.9)} date Sa 19 Nov 2022 20:44:54 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-19T20:44:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X4.5315Y-3.4787
T2
X4.124Y-4.3406
X4.6555Y-3.1988
T1
G00X4.2539Y-3.4787
M15
G01X4.2421Y-3.4787
M16
G05
T0
M30
