M48
; DRILL file {KiCad (6.0.8)} date So 30 Okt 2022 16:36:14 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-30T16:36:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.5315Y-3.4787
T1
G00X4.2539Y-3.4787
M15
G01X4.2421Y-3.4787
M16
G05
T0
M30
